import Head from "next/head";
import { Inter } from "next/font/google";
import { Main } from "../component/Main";
import { Header } from "../component/Header";
import { useCallback } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const foo = 1;

  const handleClick = useCallback((e) => {
    e.preventDefault();
    alert(foo);
  },[]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Header />

      <a href="/about.jsx" onClick={handleClick} >
        ボタン
      </a>
      
      <Main page="index" />

    </>
  );
}
